# Site settings
title: Jon
email: jonathanalbangoodman@gmail.com
description: >
  Personal homepage of Jonathan Goodman, web developer from Belfast.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jnthn.info" # the base hostname & protocol for your site
twitter_username: jonathan_alban
github_username:  jonathan-alban

# Build settings
markdown: kramdown
